# Generated by Django 6.0.2 on 2026-06-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_screener', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='screenerusage',
            new_name='stock_scree_user_id_ec718d_idx',
            old_name='stock_scree_user_id_9ba8ee_idx',
        ),
    ]
