# Generated by Django 6.0.2 on 2026-06-14 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=24, unique=True, verbose_name='종목코드')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='종목명')),
                ('market', models.CharField(db_index=True, default='KOSPI', max_length=40, verbose_name='시장')),
            ],
            options={
                'verbose_name': '종목',
                'verbose_name_plural': '종목',
                'ordering': ['market', 'name'],
                'indexes': [models.Index(fields=['market', 'name'], name='stocks_stoc_market_95686a_idx'), models.Index(fields=['code'], name='stocks_stoc_code_f8a06c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserStockStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.JSONField(blank=True, default=list, verbose_name='관심그룹')),
                ('selected_group_id', models.CharField(blank=True, default='', max_length=120, verbose_name='선택 그룹 ID')),
                ('portfolio', models.JSONField(blank=True, default=dict, verbose_name='포트폴리오')),
                ('drawing_tool_defaults', models.JSONField(blank=True, default=dict, verbose_name='드로잉 도구 기본속성')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_storage', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 관심종목 저장소',
                'verbose_name_plural': '사용자 관심종목 저장소',
            },
        ),
        migrations.CreateModel(
            name='ChartDrawingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, max_length=40, verbose_name='종목코드')),
                ('drawings', models.JSONField(blank=True, default=list, verbose_name='드로잉')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_drawing_states', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '차트 드로잉',
                'verbose_name_plural': '차트 드로잉',
                'indexes': [models.Index(fields=['user', 'stock_code'], name='stocks_char_user_id_463246_idx'), models.Index(fields=['stock_code'], name='stocks_char_stock_c_97e3a5_idx')],
                'unique_together': {('user', 'stock_code')},
            },
        ),
        migrations.CreateModel(
            name='ChartIndicatorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, max_length=40, verbose_name='종목코드')),
                ('indicators', models.JSONField(blank=True, default=list, verbose_name='지표')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_indicator_states', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '차트 지표',
                'verbose_name_plural': '차트 지표',
                'indexes': [models.Index(fields=['user', 'stock_code'], name='stocks_char_user_id_444163_idx'), models.Index(fields=['stock_code'], name='stocks_char_stock_c_7d3fc1_idx')],
                'unique_together': {('user', 'stock_code')},
            },
        ),
        migrations.CreateModel(
            name='ChartPiramidState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, max_length=40, verbose_name='종목코드')),
                ('piramid', models.JSONField(blank=True, default=dict, verbose_name='분할매수 전략')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_piramid_states', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '분할매수 전략',
                'verbose_name_plural': '분할매수 전략',
                'indexes': [models.Index(fields=['user', 'stock_code'], name='stocks_char_user_id_5a2438_idx'), models.Index(fields=['stock_code'], name='stocks_char_stock_c_c9ddb5_idx')],
                'unique_together': {('user', 'stock_code')},
            },
        ),
        migrations.CreateModel(
            name='ScreenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(db_index=True, default='', max_length=80, verbose_name='화면')),
                ('key', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='키')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='사용 횟수')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='마지막 사용일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screen_usages', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '화면 사용량',
                'verbose_name_plural': '화면 사용량',
                'indexes': [models.Index(fields=['user', 'screen'], name='stocks_scre_user_id_202bdb_idx'), models.Index(fields=['screen', 'key'], name='stocks_scre_screen_17698b_idx')],
            },
        ),
    ]
