# Generated by Django 6.0.5 on 2026-05-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('market', models.CharField(choices=[('KOSPI', 'KOSPI'), ('KOSDAQ', 'KOSDAQ'), ('KONEX', 'KONEX')], db_index=True, max_length=20)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['market', 'name'],
            },
        ),
    ]
