# Generated by Django 6.0.5 on 2026-05-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocksymbol',
            options={'ordering': ['name'], 'verbose_name': '종목', 'verbose_name_plural': '종목'},
        ),
        migrations.RemoveField(
            model_name='stocksymbol',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stocksymbol',
            name='sector',
        ),
        migrations.AlterField(
            model_name='stocksymbol',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='종목코드'),
        ),
        migrations.AlterField(
            model_name='stocksymbol',
            name='market',
            field=models.CharField(default='KOSPI', max_length=20, verbose_name='시장'),
        ),
        migrations.AlterField(
            model_name='stocksymbol',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='종목명'),
        ),
    ]
