# Generated by Django 6.0.2 on 2026-06-14 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free_1y', '초기 100명 프리미엄 1년 무료'), ('monthly', '프리미엄 월 9,900원'), ('6month', '프리미엄 6개월 49,500원')], default='free_1y', max_length=30, verbose_name='적용 플랜')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='활성화')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='시작일')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='종료일')),
                ('note', models.TextField(blank=True, default='', verbose_name='관리 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_premium_accesses', to=settings.AUTH_USER_MODEL, verbose_name='승인 관리자')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_access', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '프리미엄 이용권',
                'verbose_name_plural': '프리미엄 이용권',
                'indexes': [models.Index(fields=['is_active', 'ends_at'], name='stocks_prem_is_acti_781ab6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PremiumApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free_1y', '초기 100명 프리미엄 1년 무료'), ('monthly', '프리미엄 월 9,900원'), ('6month', '프리미엄 6개월 49,500원')], default='free_1y', max_length=30, verbose_name='신청 플랜')),
                ('status', models.CharField(choices=[('pending', '승인 대기'), ('approved', '승인 완료'), ('rejected', '반려'), ('cancelled', '취소')], db_index=True, default='pending', max_length=20, verbose_name='상태')),
                ('user_message', models.TextField(blank=True, default='', verbose_name='사용자 메모')),
                ('admin_reply', models.TextField(blank=True, default='', help_text='승인/반려 후 사용자 화면에 표시됩니다.', verbose_name='관리자 답장')),
                ('source', models.CharField(blank=True, default='', max_length=80, verbose_name='신청 위치')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('approved_until', models.DateTimeField(blank=True, null=True, verbose_name='프리미엄 만료 예정일')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_premium_applications', to=settings.AUTH_USER_MODEL, verbose_name='처리 관리자')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_application', to=settings.AUTH_USER_MODEL, verbose_name='신청 사용자')),
            ],
            options={
                'verbose_name': '프리미엄 1년 무료 신청',
                'verbose_name_plural': '프리미엄 1년 무료 신청 목록',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='stocks_prem_status_b1940a_idx'), models.Index(fields=['plan', 'status'], name='stocks_prem_plan_2c6cfb_idx')],
            },
        ),
    ]
