# Generated by Django 6.0.2 on 2026-06-05 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_chartpiramidstate_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartDrawingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, max_length=20, verbose_name='종목코드')),
                ('drawings', models.JSONField(blank=True, default=list, verbose_name='드로잉 데이터')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '빗각뷰 차트 드로잉',
                'verbose_name_plural': '빗각뷰 차트 드로잉',
            },
        ),
        migrations.CreateModel(
            name='UserStockStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.JSONField(blank=True, default=list, verbose_name='관심종목 그룹')),
                ('selected_group_id', models.CharField(blank=True, default='', max_length=120, verbose_name='선택 그룹 ID')),
                ('portfolio', models.JSONField(blank=True, default=dict, verbose_name='포트폴리오')),
                ('drawing_tool_defaults', models.JSONField(blank=True, default=dict, verbose_name='드로잉 도구 기본속성')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '빗각뷰 사용자 저장 데이터',
                'verbose_name_plural': '빗각뷰 사용자 저장 데이터',
            },
        ),
        migrations.RenameIndex(
            model_name='chartindicatorstate',
            new_name='stocks_char_user_id_444163_idx',
            old_name='stocks_char_user_id_6a8f_idx',
        ),
        migrations.AddIndex(
            model_name='chartpiramidstate',
            index=models.Index(fields=['user', 'stock_code'], name='stocks_char_user_id_5a2438_idx'),
        ),
        migrations.AddField(
            model_name='chartdrawingstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitgak_chart_drawings', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='userstockstorage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitgak_stock_storage', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='chartdrawingstate',
            index=models.Index(fields=['user', 'stock_code'], name='stocks_char_user_id_463246_idx'),
        ),
        migrations.AddConstraint(
            model_name='chartdrawingstate',
            constraint=models.UniqueConstraint(fields=('user', 'stock_code'), name='uniq_bitgak_chart_drawing_user_stock'),
        ),
    ]
