# Generated by Django 6.0.2 on 2026-06-05 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeKeywordSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=120, verbose_name='검색어')),
                ('search_type', models.CharField(choices=[('shorts', '쇼츠용 키워드'), ('longform', '일반 유튜브 키워드')], default='shorts', max_length=20, verbose_name='분석 유형')),
                ('category', models.CharField(choices=[('all', '전체'), ('stock', '주식'), ('economy', '경제'), ('life', '생활'), ('living', '리빙'), ('parenting', '육아'), ('travel', '여행'), ('it', 'IT'), ('game', '게임'), ('sidejob', '부업'), ('car', '자동차'), ('etc', '기타')], default='all', max_length=30, verbose_name='카테고리')),
                ('result_json', models.JSONField(blank=True, default=dict, verbose_name='분석 결과')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_keyword_searches', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '유튜브 키워드 검색 기록',
                'verbose_name_plural': '유튜브 키워드 검색 기록',
                'ordering': ['-created_at'],
            },
        ),
    ]
