# Generated by ChatGPT for youtube_keyword access quota and admin premium grants.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("youtube_keyword", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YoutubeKeywordDailyUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name="사용일")),
                ("search_count", models.PositiveIntegerField(default=0, verbose_name="검색 횟수")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="youtube_keyword_daily_usages", to=settings.AUTH_USER_MODEL, verbose_name="사용자")),
            ],
            options={
                "verbose_name": "유튜브 키워드 일일 사용량",
                "verbose_name_plural": "유튜브 키워드 일일 사용량",
                "ordering": ["-date", "-updated_at"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="YoutubeKeywordPremiumGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("starts_at", models.DateField(blank=True, null=True, verbose_name="시작일")),
                ("expires_at", models.DateField(blank=True, null=True, verbose_name="만료일")),
                ("memo", models.CharField(blank=True, default="", max_length=255, verbose_name="관리자 메모")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="youtube_keyword_grants_created", to=settings.AUTH_USER_MODEL, verbose_name="승인 관리자")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="youtube_keyword_premium_grants", to=settings.AUTH_USER_MODEL, verbose_name="사용자")),
            ],
            options={
                "verbose_name": "유튜브 키워드 프리미엄 승인",
                "verbose_name_plural": "유튜브 키워드 프리미엄 승인",
                "ordering": ["-created_at"],
            },
        ),
    ]
