# Generated by Django 6.0.2 on 2026-05-17 08:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.TextField(blank=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('bot_status', models.CharField(choices=[('human', 'Human'), ('bot', 'Bot'), ('suspicious', 'Suspicious')], db_index=True, default='human', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='analytics_v_created_9567f8_idx'), models.Index(fields=['ip_address'], name='analytics_v_ip_addr_dbc52d_idx'), models.Index(fields=['bot_status'], name='analytics_v_bot_sta_a6bbd2_idx'), models.Index(fields=['path'], name='analytics_v_path_5f6363_idx')],
            },
        ),
    ]
