# Generated by Django 6.0.2 on 2026-05-18 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitlog',
            options={'ordering': ['-last_seen_at', '-created_at'], 'verbose_name': 'Visit Log', 'verbose_name_plural': 'Visit Logs'},
        ),
        migrations.RemoveIndex(
            model_name='visitlog',
            name='analytics_v_created_9567f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitlog',
            name='analytics_v_ip_addr_dbc52d_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitlog',
            name='analytics_v_bot_sta_a6bbd2_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitlog',
            name='analytics_v_path_5f6363_idx',
        ),
        migrations.AddField(
            model_name='visitlog',
            name='first_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='last_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='request_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='user_agent_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='visit_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='bot_status',
            field=models.CharField(choices=[('human', 'Human'), ('bot', 'Bot'), ('suspicious', 'Suspicious'), ('blocked', 'Blocked')], db_index=True, default='human', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='path',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['visit_date', 'bot_status'], name='analytics_v_visit_d_b1d92c_idx'),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['visit_date', 'ip_address'], name='analytics_v_visit_d_3345f5_idx'),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['visit_date', 'path'], name='analytics_v_visit_d_981750_idx'),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['ip_address', 'path', 'visit_date'], name='analytics_v_ip_addr_22d4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['last_seen_at'], name='analytics_v_last_se_0f6401_idx'),
        ),
    ]
