# Generated by Django 6.0.2 on 2026-05-17 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='쿠폰 코드')),
                ('days', models.PositiveIntegerField(default=14, verbose_name='지급 일수')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='최대 사용 횟수')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='사용 횟수')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='시작일')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='종료일')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '프리미엄 쿠폰',
                'verbose_name_plural': '프리미엄 쿠폰',
            },
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', '무료'), ('premium', '프리미엄')], default='free', max_length=20, verbose_name='요금제')),
                ('premium_until', models.DateTimeField(blank=True, null=True, verbose_name='프리미엄 만료일')),
                ('indicator_limit', models.PositiveIntegerField(default=2, verbose_name='지표 제한')),
                ('watchlist_limit', models.PositiveIntegerField(default=10, verbose_name='관심종목 제한')),
                ('group_limit', models.PositiveIntegerField(default=1, verbose_name='종목그룹 제한')),
                ('drawing_limit', models.PositiveIntegerField(default=10, verbose_name='드로잉 저장 제한')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitgak_access', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 이용권',
                'verbose_name_plural': '사용자 이용권',
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='사용일')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='access.coupon', verbose_name='쿠폰')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '쿠폰 사용내역',
                'verbose_name_plural': '쿠폰 사용내역',
                'unique_together': {('coupon', 'user')},
            },
        ),
    ]
