# Generated by Django 6.0.2 on 2026-05-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, help_text='0이면 무제한 사용', verbose_name='최대 사용 횟수'),
        ),
    ]
