# Generated by Django 6.0.2 on 2026-06-14 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_coupon_max_uses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=80, unique=True, verbose_name='쿠폰 코드'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='days',
            field=models.PositiveIntegerField(default=30, verbose_name='지급 일수'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, verbose_name='최대 사용 횟수'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='memo',
            field=models.TextField(blank=True, verbose_name='메모'),
        ),
        migrations.AlterField(
            model_name='couponredemption',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='access.coupon', verbose_name='쿠폰'),
        ),
        migrations.AlterField(
            model_name='couponredemption',
            name='redeemed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.CreateModel(
            name='PremiumApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free_365', '초기 100명 프리미엄 1년 무료'), ('monthly_9900', '프리미엄 월 9,900원'), ('six_month_49500', '프리미엄 6개월 49,500원')], default='free_365', max_length=32, verbose_name='신청 플랜')),
                ('status', models.CharField(choices=[('pending', '승인 대기'), ('approved', '승인 완료'), ('rejected', '반려')], default='pending', max_length=20, verbose_name='상태')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='신청 위치')),
                ('user_message', models.TextField(blank=True, verbose_name='사용자 메모')),
                ('admin_reply', models.TextField(blank=True, default='', help_text='승인/반려 후 사용자가 로그인하면 이 내용이 모달로 표시됩니다.', verbose_name='관리자 답장')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일')),
                ('notice_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='사용자 확인일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_premium_applications', to=settings.AUTH_USER_MODEL, verbose_name='승인 관리자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_applications', to=settings.AUTH_USER_MODEL, verbose_name='신청 사용자')),
            ],
            options={
                'verbose_name': '프리미엄 1년 무료 신청',
                'verbose_name_plural': '프리미엄 1년 무료 신청',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='access_prem_user_id_9936cc_idx'), models.Index(fields=['created_at'], name='access_prem_created_d9a6bd_idx')],
            },
        ),
    ]
