# Generated by Django 6.0.2 on 2026-06-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_coupon_code_alter_coupon_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumapplication',
            name='status',
            field=models.CharField(choices=[('pending', '승인 대기'), ('approved', '승인 완료'), ('rejected', '반려'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태'),
        ),
    ]
