# Generated by Django 6.0.2 on 2026-05-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsightPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('youtube', '유튜브 관점'), ('note', '일반 관점'), ('market', '시장 관점')], default='youtube', max_length=20, verbose_name='콘텐츠 유형')),
                ('title', models.CharField(max_length=120, verbose_name='제목')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=160, unique=True, verbose_name='주소 슬러그')),
                ('eyebrow', models.CharField(blank=True, help_text='예: 삼성전자 관점, 코스피 흐름, 빗각 분석', max_length=50, verbose_name='상단 라벨')),
                ('summary', models.CharField(blank=True, max_length=220, verbose_name='짧은 설명')),
                ('content', models.TextField(blank=True, help_text='유튜브 영상과 연결할 관점 설명을 적어주세요.', verbose_name='본문')),
                ('youtube_url', models.URLField(blank=True, help_text='유튜브 영상, 쇼츠 주소를 넣으면 썸네일과 임베드가 자동 처리됩니다.', verbose_name='유튜브 URL')),
                ('thumbnail_url', models.URLField(blank=True, help_text='비워두면 유튜브 썸네일을 자동 사용합니다.', verbose_name='커스텀 썸네일 URL')),
                ('related_symbol', models.CharField(blank=True, help_text='예: 005930', max_length=20, verbose_name='관련 종목코드')),
                ('related_name', models.CharField(blank=True, help_text='예: 삼성전자', max_length=80, verbose_name='관련 종목명')),
                ('tags', models.CharField(blank=True, help_text='쉼표로 구분하세요. 예: 지지선, 저항선, 코스피, 삼성전자', max_length=200, verbose_name='태그')),
                ('risk_notice', models.CharField(default='본 콘텐츠는 학습 및 관점 공유용이며, 특정 종목의 매수·매도 추천이 아닙니다.', max_length=220, verbose_name='고지 문구')),
                ('is_featured', models.BooleanField(default=True, verbose_name='캐러셀 노출')),
                ('is_published', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='노출 순서')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='공개일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '빗각관점',
                'verbose_name_plural': '빗각관점',
                'ordering': ['display_order', '-published_at', '-created_at'],
            },
        ),
    ]
