# Generated by Django 6.0.2 on 2026-05-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightpost',
            name='cover_image',
            field=models.FileField(blank=True, help_text='글 카드와 상세 페이지에 표시할 이미지입니다.', null=True, upload_to='insights/%Y/%m/', verbose_name='대표 이미지'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='content',
            field=models.TextField(blank=True, verbose_name='본문'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='content_type',
            field=models.CharField(choices=[('note', '관점 글'), ('youtube', '유튜브 링크 포함'), ('market', '시장 관점')], default='note', max_length=20, verbose_name='콘텐츠 유형'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=50, verbose_name='상단 라벨'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='related_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='관련 종목명'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='related_symbol',
            field=models.CharField(blank=True, max_length=20, verbose_name='관련 종목코드'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=180, unique=True, verbose_name='주소 슬러그'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='태그'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='thumbnail_url',
            field=models.URLField(blank=True, verbose_name='외부 썸네일 URL'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='선택사항입니다. 상세 페이지 하단에 자연스럽게 링크로 표시됩니다.', verbose_name='유튜브 URL'),
        ),
    ]
