# Generated by Django 6.0.2 on 2026-05-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_insightpost_cover_image_alter_insightpost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightpost',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='선택사항입니다. 상세 페이지 하단에 링크 버튼으로 표시됩니다.', verbose_name='유튜브 URL'),
        ),
    ]
