# Generated by Django 6.0.2 on 2026-05-23 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_alter_insightpost_youtube_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insightpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitgak_insight_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='content_type',
            field=models.CharField(choices=[('youtube', '유튜브 관점'), ('note', '일반 관점'), ('market', '시장 관점')], default='note', max_length=20, verbose_name='콘텐츠 유형'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='insights/%Y/%m/', verbose_name='대표 이미지'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=60, verbose_name='상단 라벨'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='공개 여부'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='related_name',
            field=models.CharField(blank=True, max_length=90, verbose_name='관련 종목명'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='related_symbol',
            field=models.CharField(blank=True, max_length=30, verbose_name='관련 종목코드'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='risk_notice',
            field=models.CharField(default='본 콘텐츠는 학습 및 관점 공유용이며, 특정 종목의 매수·매도 추천이 아닙니다.', max_length=260, verbose_name='고지 문구'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='summary',
            field=models.CharField(blank=True, max_length=260, verbose_name='짧은 설명'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='tags',
            field=models.CharField(blank=True, max_length=240, verbose_name='태그'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='thumbnail_url',
            field=models.URLField(blank=True, verbose_name='커스텀 썸네일 URL'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='title',
            field=models.CharField(max_length=160, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='유튜브 URL'),
        ),
    ]
