# Generated by Django 6.0.2 on 2026-05-31 01:29

import apps.insights.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0004_insightpost_author_alter_insightpost_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insightpost',
            name='author',
        ),
        migrations.AddField(
            model_name='insightpost',
            name='chart_api_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='차트 API URL'),
        ),
        migrations.AddField(
            model_name='insightpost',
            name='chart_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='차트 종목코드'),
        ),
        migrations.AddField(
            model_name='insightpost',
            name='chart_interval',
            field=models.CharField(blank=True, default='1d', max_length=20, verbose_name='차트 시간봉'),
        ),
        migrations.AddField(
            model_name='insightpost',
            name='chart_name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='차트 종목명'),
        ),
        migrations.AddField(
            model_name='insightpost',
            name='chart_snapshot',
            field=models.TextField(blank=True, default='', verbose_name='차트 스냅샷'),
        ),
        migrations.AddField(
            model_name='insightpost',
            name='media_type',
            field=models.CharField(choices=[('image', '이미지 방식'), ('chart', '차트 방식')], default='image', max_length=20, verbose_name='표시 방식'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='content',
            field=models.TextField(verbose_name='본문'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.insights.models.insight_cover_upload_to, verbose_name='대표 이미지'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='related_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='관련 종목명'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='related_symbol',
            field=models.CharField(blank=True, max_length=20, verbose_name='관련 종목코드'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='risk_notice',
            field=models.CharField(default='본 콘텐츠는 학습 및 관점 공유용이며, 특정 종목의 매수·매도 추천이 아닙니다.', max_length=240, verbose_name='고지 문구'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='summary',
            field=models.CharField(blank=True, max_length=240, verbose_name='짧은 설명'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='tags',
            field=models.CharField(blank=True, max_length=220, verbose_name='태그'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='title',
            field=models.CharField(max_length=140, verbose_name='제목'),
        ),
    ]
