# Generated by Django 6.0.2 on 2026-06-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0005_remove_insightpost_author_insightpost_chart_api_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightpost',
            name='chart_api_url',
            field=models.CharField(blank=True, max_length=240, verbose_name='차트 API URL'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='chart_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='차트 종목코드'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='chart_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='차트 종목명'),
        ),
        migrations.AlterField(
            model_name='insightpost',
            name='chart_snapshot',
            field=models.TextField(blank=True, verbose_name='차트 저장 스냅샷'),
        ),
    ]
